In [ ]:
# Dimentionality reduction Techniques
1. Feature Selection
2. Feature Extraction
    a. Principal Component Analysis
    b. LDA

## Principal Component Analysis

In [ ]:
This is Feature Extraction Technique.
Exctracting information from existing set of features and creating new dataset for further operation.

# This is unsupervised machine learning technique.

In [1]:
from sklearn.datasets import load_iris

import pandas as pd
import numpy as np

In [2]:
data = load_iris()

df = pd.DataFrame(data.data, columns=data.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [3]:
df.corr()  # Strenghth

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000

## 1. Find Covariance matrix

In [4]:
df.cov()  # Spread + Direction

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           0.685694         -0.042434           1.274315   
sepal width (cm)           -0.042434          0.189979          -0.329656   
petal length (cm)           1.274315         -0.329656           3.116278   
petal width (cm)            0.516271         -0.121639           1.295609   

                   petal width (cm)  
sepal length (cm)          0.516271  
sepal width (cm)          -0.121639  
petal length (cm)          1.295609  
petal width (cm)           0.581006

In [5]:
df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [6]:
# Covariance of column with itself gives variance

## 2. Eigen Decomposition

In [ ]:
1. Eigen Values
2. Eigen Vectors

In [ ]:
AX = lambda * I * X = 0

(A - lambda * I) = 0

In [7]:
from numpy.polynomial import Polynomial

# x2 - 5x - 6 = 0  --> x1 = 6, x2 = -1

a = 1
b = -5
c = -6

p1 = Polynomial([c,b,a])
p1

Polynomial([-6., -5.,  1.], domain=[-1,  1], window=[-1,  1])

In [8]:
p1.roots()

array([-1.,  6.])

In [9]:
p1 = Polynomial([8,9,2])
p1.roots()

array([-3.28077641, -1.21922359])

### Eigen Values

In [12]:
matrix = np.random.randint(10,20, size = (3,3))
matrix   # 3 * 3

array([[18, 16, 12],
       [18, 17, 17],
       [14, 15, 12]])

In [13]:
eig_val = np.linalg.eigvals(matrix) # 3
eig_val

array([46.59424036,  2.18964161, -1.78388197])

### Eigen Vector

In [14]:
eigen_val, eig_vect = np.linalg.eig(matrix)
eigen_val

array([46.59424036,  2.18964161, -1.78388197])

In [17]:
eig_vect

array([[ 0.5730018 ,  0.78097287,  0.30303241],
       [ 0.64150207, -0.43719322, -0.78257141],
       [ 0.51004317, -0.44603079,  0.5438321 ]])

In [18]:
eig_vect[0]   # 1 * 3

array([0.5730018 , 0.78097287, 0.30303241])

In [19]:
eig_vect[1]  # 1 * 3

array([ 0.64150207, -0.43719322, -0.78257141])

In [ ]:
# On Iris Dataset

In [24]:
matrix = df.cov()  # 4 * 4
matrix

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           0.685694         -0.042434           1.274315   
sepal width (cm)           -0.042434          0.189979          -0.329656   
petal length (cm)           1.274315         -0.329656           3.116278   
petal width (cm)            0.516271         -0.121639           1.295609   

                   petal width (cm)  
sepal length (cm)          0.516271  
sepal width (cm)          -0.121639  
petal length (cm)          1.295609  
petal width (cm)           0.581006

In [23]:
eig_val = np.linalg.eigvals(matrix) # 4
eig_val

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [25]:
eigen_val, eig_vect = np.linalg.eig(matrix)
eig_vect     # 4 * 4

array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
       [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
       [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
       [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]])

In [26]:
# 1st PC1
eig_vect[0]   # Size 1 * 4

array([ 0.36138659, -0.65658877, -0.58202985,  0.31548719])

In [27]:
# 2nd PC2
eig_vect[1]   # Size 1 * 4

array([-0.08452251, -0.73016143,  0.59791083, -0.3197231 ])

In [28]:
# 3rd PC3
eig_vect[2]   # Size 1 * 4

array([ 0.85667061,  0.17337266,  0.07623608, -0.47983899])

In [29]:
# 4th PC4
eig_vect[3]   # Size 1 * 4

array([0.3582892 , 0.07548102, 0.54583143, 0.75365743])

#### Trasformation into original shape

In [ ]:
Original data Size = 150 rows × 4 columns

Eigen Values = 4

Eigen Vector = 1 * 4
Transpose Eigen Vector = 4 * 1

PC1 = (150 * 4) . (4 * 1)
PC1 = 150 * 1


PC1   PC2   PC3   PC4
0.84  0.11  0.01 0.2


PC1   PC2 <-- This Principal Components giving maximum variance